# Python basics last class - week 3, packages and arrays


In [ ]:
! python -m pip install numpy

## Import numpy

In [ ]:
import numpy
import numpy as np
from numpy import arange

### creating arrays

In [ ]:
import numpy as np

list = [1, 5, 8, 10, 3]
print(list)

array = np.array(list)
print(array)

print(list * 2)
print(array * 2)

list.append(2)
#array.add(2) --> not possible

# 1D arrays
print(np.arange(10)) # fill an array with the number from 0 up until the given values (not included)
print(np.zeros(15))# fill an array with x number of zeros
print(np.ones(10)) # fill an array with x number of ones
print(np.full(10, 23)) #fill an array of x size with y number

print(np.random.randint(-5, 6, 10)) #array of random ints between lower and top values, top values not included
print(np.random.random(15)) #15 random floats between 0 and 1


[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[23 23 23 23 23 23 23 23 23 23]
[ 2 -4 -2 -3  2  1  0  4  5  3]
[0.07438921 0.96200782 0.21166213 0.2488944  0.47269918 0.72899537
 0.3255691  0.52398782 0.61851368 0.60795964 0.09214584 0.5979849
 0.24252006 0.41155226 0.43845286]


## Reshaping and converting and array

In [47]:
import numpy as np
array = np.random.randint(-5, 6, 10)
print(array)
print(array.shape)
print(array.ndim)
print(array.dtype)

#conversion
arrayOfFloats = array.astype('D')
print(arrayOfFloats)
# i - integer / b - boolean / f - float / M - DateTime / S - string / can also work with str, bool, int, ...

arrayofStrings = array.astype(str)
print(arrayofStrings)

array2D = np.reshape(array, (5,2))
print(array2D)
array2D = np.reshape(array, (2,5))
print(array2D)
array2D = np.reshape(array, (10,1))
print(array2D)

#array2D = np.reshape(array, (3,3))
print(array2D)

[ 2  5  3  1  1  5  1 -1 -1  2]
(10,)
1
int32
[ 2.+0.j  5.+0.j  3.+0.j  1.+0.j  1.+0.j  5.+0.j  1.+0.j -1.+0.j -1.+0.j
  2.+0.j]
['2' '5' '3' '1' '1' '5' '1' '-1' '-1' '2']
[[ 2  5]
 [ 3  1]
 [ 1  5]
 [ 1 -1]
 [-1  2]]
[[ 2  5  3  1  1]
 [ 5  1 -1 -1  2]]
[[ 2]
 [ 5]
 [ 3]
 [ 1]
 [ 1]
 [ 5]
 [ 1]
 [-1]
 [-1]
 [ 2]]
[[ 2]
 [ 5]
 [ 3]
 [ 1]
 [ 1]
 [ 5]
 [ 1]
 [-1]
 [-1]
 [ 2]]


## Slicing arrays
[start : end : step]
- start is the starting index
- end is the ending index not included
- step is the stepsize

In [65]:
import numpy as np
array = np.array([6, 8, 2, 9, 3, 1, 4, 7, 0, 5])
print(array)
print(array[1:5:1])
print(array[1:5:])
print(array[1:5:2])
print(array[0:5:2])
print(array[:5:2])

print(array[::3])
print(array[5::])

print(array[::-1])
print(array[-9:-1:])

print(array[0:10:-1])
print(array[5::-1])
print(array[::-2])

[6 8 2 9 3 1 4 7 0 5]
[8 2 9 3]
[8 2 9 3]
[8 9]
[6 2 3]
[6 2 3]
[6 9 4 5]
[1 4 7 0 5]
[5 0 7 4 1 3 9 2 8 6]
[8 2 9 3 1 4 7 0]
[]
[1 3 9 2 8 6]
[5 7 1 9 8]


### exercise on slicing
generate a list of 24 temperatures, one for every hour of the day.
Isolate the specific parts of the day and analyse them with slicing.

-Make a list of the 24 tempartures (random ints)
-slice these parts
* morning rush: first 6 hours of the day
* late evening: last 4  hours
* trend: every 3 hours -> 00.00, 03.00, 06.00
* lunchbreak: 12.00 - 18.00 (REVERSED)